<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\DiagnosticQuestion;

class DiagnosticQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $questions = [
            // Excel questions
            [
                'category' => 'excel',
                'question' => '¿Qué es Excel?',
                'option_a' => 'Un programa para escribir textos',
                'option_b' => 'Un programa para realizar cálculos matemáticos y estadísticos',
                'option_c' => 'Un programa para dibujar',
                'option_d' => 'Un programa para gestionar bases de datos',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'excel',
                'question' => '¿Por qué elementos está compuesto un libro de Excel?',
                'option_a' => 'Cuadernos',
                'option_b' => 'Documentos',
                'option_c' => 'Hojas',
                'option_d' => 'Libretas',
                'correct_answer' => 'c',
            ],
            [
                'category' => 'excel',
                'question' => '¿Qué es una celda?',
                'option_a' => 'La intersección de una fila y una columna',
                'option_b' => 'Un conjunto de filas',
                'option_c' => 'Un conjunto de columnas',
                'option_d' => 'Ninguna de las anteriores',
                'correct_answer' => 'a',
            ],
            [
                'category' => 'excel',
                'question' => 'Por defecto, ¿cómo se identifican las filas y las columnas?',
                'option_a' => 'Filas con letras y columnas con números',
                'option_b' => 'Filas con letras y columnas con números romanos',
                'option_c' => 'Filas con números romanos y columnas con letras',
                'option_d' => 'Filas con números y columnas con letras',
                'correct_answer' => 'd',
            ],
            [
                'category' => 'excel',
                'question' => 'En una celda de Excel, se puede introducir…',
                'option_a' => 'Números',
                'option_b' => 'Fórmulas',
                'option_c' => 'Textos',
                'option_d' => 'Todas las anteriores',
                'correct_answer' => 'd',
            ],
            [
                'category' => 'excel',
                'question' => '¿Qué símbolo hay que introducir para comenzar a escribir una fórmula?',
                'option_a' => '$',
                'option_b' => '=',
                'option_c' => '-',
                'option_d' => 'Ninguno',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'excel',
                'question' => '¿Se pueden ocultar filas y columnas sin perder información?',
                'option_a' => 'No',
                'option_b' => 'Sólo filas',
                'option_c' => 'Sólo columnas',
                'option_d' => 'Sí',
                'correct_answer' => 'd',
            ],
            [
                'category' => 'excel',
                'question' => '¿Cuál de las siguientes fórmulas es correcta para sumar 10 celdas?',
                'option_a' => '=Suma(A1:A10)',
                'option_b' => '=Suma(A10:A1)',
                'option_c' => '=Suma(1A:10A)',
                'option_d' => '=Suma(A1;A10)',
                'correct_answer' => 'a',
            ],
            [
                'category' => 'excel',
                'question' => 'Si en una celda aparecen símbolos de almohadilla (#####):',
                'option_a' => 'Está en notación científica negativa',
                'option_b' => 'Es un valor de texto incorrecto',
                'option_c' => 'El valor no cabe en el ancho de la celda',
                'option_d' => 'Ninguna es correcta',
                'correct_answer' => 'c',
            ],
            [
                'category' => 'excel',
                'question' => '¿Cuál es la forma más rápida de sumar 10 celdas?',
                'option_a' => 'Seleccionar sólo las primeras 3 celdas y aplicar autosuma',
                'option_b' => '=A1+A2+A3+A4+A5+A6+A7+A8+A9+A10',
                'option_c' => 'Seleccionar las 10 celdas y aplicar autosuma',
                'option_d' => 'Ninguna de las anteriores',
                'correct_answer' => 'c',
            ],
            [
                'category' => 'excel',
                'question' => 'Para restar dos celdas, la fórmula correcta es:',
                'option_a' => '=RESTA(D4-E4)',
                'option_b' => '=D4-E4',
                'option_c' => '=DIFERENCIA(D4;E4)',
                'option_d' => '=RESTAR(D4-E4)',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'excel',
                'question' => '¿Se puede crear en Excel una base de datos de solo texto?',
                'option_a' => 'Verdadero',
                'option_b' => 'Falso',
                'option_c' => 'Solo si tiene formato tabla',
                'option_d' => 'Solo con validación de datos',
                'correct_answer' => 'a',
            ],
            [
                'category' => 'excel',
                'question' => 'La fórmula correcta para dividir es:',
                'option_a' => '=(A3/A5)',
                'option_b' => '=div(A3:A5)',
                'option_c' => '(A3*A5)',
                'option_d' => '=(A3^A5)',
                'correct_answer' => 'a',
            ],
            [
                'category' => 'excel',
                'question' => '¿Cuál es el resultado de la operación: =(8 - (6+2))/2?',
                'option_a' => '4',
                'option_b' => '0',
                'option_c' => '1',
                'option_d' => '-4',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'excel',
                'question' => 'La función =SUMA(A1;3;A8):',
                'option_a' => 'Suma 3 veces la celda A1 y la A8',
                'option_b' => 'Suma la celda A1 y 3 veces la celda A8',
                'option_c' => 'No es una fórmula correcta',
                'option_d' => 'Suma la celda A1, el número 3 y la celda A8',
                'correct_answer' => 'd',
            ],
            // Power BI questions
            [
                'category' => 'powerbi',
                'question' => '¿Qué herramienta permite limpiar, transformar y combinar datos dentro de Power BI?',
                'option_a' => 'Panel de campos',
                'option_b' => 'Power Query',
                'option_c' => 'Modelado',
                'option_d' => 'Visualizaciones',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué es una medida en DAX?',
                'option_a' => 'Un valor estático',
                'option_b' => 'Un cálculo dinámico basado en el contexto',
                'option_c' => 'Una columna',
                'option_d' => 'Un filtro',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué tipo de visualización conviene para mostrar tendencias a lo largo del tiempo?',
                'option_a' => 'Mapa',
                'option_b' => 'Gráfico de líneas',
                'option_c' => 'Matriz',
                'option_d' => 'Dispersión',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué se usa para conectar tablas relacionadas?',
                'option_a' => 'Medidas',
                'option_b' => 'Relaciones',
                'option_c' => 'Panel de filtros',
                'option_d' => 'Visualizaciones',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué permite la vista de Modelado?',
                'option_a' => 'Crear dashboards',
                'option_b' => 'Crear relaciones y medidas',
                'option_c' => 'Exportar informes',
                'option_d' => 'Cambiar temas',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué tabla es fundamental para trabajar con funciones de inteligencia temporal?',
                'option_a' => 'Tabla resumen',
                'option_b' => 'Tabla de medidas',
                'option_c' => 'Tabla calendario',
                'option_d' => 'Tabla duplicada',
                'correct_answer' => 'c',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Cuál es la función principal de Power BI Desktop?',
                'option_a' => 'Ejecutar flujos',
                'option_b' => 'Crear y transformar modelos de datos',
                'option_c' => 'Compartir informes',
                'option_d' => 'Definir permisos',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué visualización es ideal para comparar proporciones?',
                'option_a' => 'Dispersión',
                'option_b' => 'Torta',
                'option_c' => 'Línea',
                'option_d' => 'Mapa',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué es un slicer?',
                'option_a' => 'Un tipo de medida',
                'option_b' => 'Un filtro visual',
                'option_c' => 'Un tipo de archivo',
                'option_d' => 'Un conector',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Para qué sirve CALCULATE en DAX?',
                'option_a' => 'Importar datos',
                'option_b' => 'Cambiar el contexto de cálculo',
                'option_c' => 'Crear gráficos',
                'option_d' => 'Ordenar columnas',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué opción permite que un reporte en Power BI se actualice automáticamente desde la nube?',
                'option_a' => 'Exportar',
                'option_b' => 'Actualización programada',
                'option_c' => 'Publicar manualmente cada día',
                'option_d' => 'Convertir a Excel',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué tipo de gráfico es más útil para comparar categorías?',
                'option_a' => 'Columnas',
                'option_b' => 'Area',
                'option_c' => 'Torta',
                'option_d' => 'Tarjeta',
                'correct_answer' => 'a',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué beneficio tiene usar Power BI para análisis de datos?',
                'option_a' => 'Editar documentos',
                'option_b' => 'Visualizar datos interactivos y conectados',
                'option_c' => 'Crear macros',
                'option_d' => 'Gestión de usuarios',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué se obtiene al crear una relación "uno a muchos"?',
                'option_a' => 'Un filtro',
                'option_b' => 'Un gráfico',
                'option_c' => 'La conexión entre tablas clave',
                'option_d' => 'Una medida',
                'correct_answer' => 'c',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué función permite combinar datos de muchas fuentes distintas?',
                'option_a' => 'Relacionar',
                'option_b' => 'Power Query',
                'option_c' => 'Medidas',
                'option_d' => 'Mapas',
                'correct_answer' => 'b',
            ],
            // Power Automate questions
            [
                'category' => 'powerautomate',
                'question' => '¿Qué es un flujo automatizado?',
                'option_a' => 'Un proceso manual',
                'option_b' => 'Un proceso que se ejecuta cuando ocurre un evento',
                'option_c' => 'Un archivo comprimido',
                'option_d' => 'Un gráfico',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué es un trigger?',
                'option_a' => 'Un paso final',
                'option_b' => 'El evento que activa un flujo',
                'option_c' => 'Una notificación',
                'option_d' => 'Una conexión',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué es un conector en Power Automate?',
                'option_a' => 'Un archivo',
                'option_b' => 'Una aplicación externa que se integra con el flujo',
                'option_c' => 'Un gráfico',
                'option_d' => 'Una carpeta',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué tipo de flujo se activa en un horario definido?',
                'option_a' => 'Flujo automático',
                'option_b' => 'Flujo instantáneo',
                'option_c' => 'Flujo programado',
                'option_d' => 'Flujo de escritorio',
                'correct_answer' => 'c',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué permite la acción "Enviar un correo (V2)" en Outlook?',
                'option_a' => 'Ejecutar consultas',
                'option_b' => 'Notificar automáticamente',
                'option_c' => 'Crear tablas',
                'option_d' => 'Exportar datos',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué tipo de flujo permite ejecutarse con un botón en el móvil?',
                'option_a' => 'Flujo automático',
                'option_b' => 'Flujo instantáneo',
                'option_c' => 'Flujo programado',
                'option_d' => 'Flujo de escritorio',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué debes revisar cuando un flujo falla?',
                'option_a' => 'Historial del flujo y detalles del error',
                'option_b' => 'Ubicación del archivo',
                'option_c' => 'El panel de visualización',
                'option_d' => 'Conexiones de Power BI',
                'correct_answer' => 'a',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué acción permite crear un registro en una lista de SharePoint?',
                'option_a' => 'Crear ítem',
                'option_b' => 'Exportar tabla',
                'option_c' => 'Combinar archivos',
                'option_d' => 'Filtrar datos',
                'correct_answer' => 'a',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué es un flujo de escritorio?',
                'option_a' => 'Un programa de gráficos',
                'option_b' => 'Una automatización local con acciones del computador',
                'option_c' => 'Un panel de análisis',
                'option_d' => 'Un conector externo',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué permite la acción "Agregar fila a una tabla" en Excel Online?',
                'option_a' => 'Crear una tabla dinámica',
                'option_b' => 'Insertar datos automáticamente',
                'option_c' => 'Ejecutar consultas SQL',
                'option_d' => 'Aplicar formato',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué caracteriza a un flujo automático?',
                'option_a' => 'Se ejecuta con un botón',
                'option_b' => 'Se activa según un evento externo',
                'option_c' => 'Se ejecuta en un horario',
                'option_d' => 'Solo funciona en escritorio',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué debes tener para usar un conector premium?',
                'option_a' => 'Permisos del equipo',
                'option_b' => 'Licencias adicionales',
                'option_c' => 'Un archivo PDF',
                'option_d' => 'Una cuenta de Gmail',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué permite Power Automate en una organización?',
                'option_a' => 'Crear dashboards',
                'option_b' => 'Automatizar procesos repetitivos',
                'option_c' => 'Extraer datos de bases clínicas',
                'option_d' => 'Convertir archivos',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué herramienta permite monitorear el comportamiento del flujo paso a paso?',
                'option_a' => 'Editor de Excel',
                'option_b' => 'Historial del flujo',
                'option_c' => 'Power BI',
                'option_d' => 'OneDrive',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué opción es necesaria para que un flujo funcione correctamente?',
                'option_a' => 'Un tema de color',
                'option_b' => 'Un trigger inicial',
                'option_c' => 'Un archivo en PDF',
                'option_d' => 'Una cuenta local',
                'correct_answer' => 'b',
            ],
        ];

        foreach ($questions as $question) {
            DiagnosticQuestion::create($question);
        }
    }
}
