<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\DiagnosticQuestion;

class DiagnosticQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Eliminar todas las preguntas existentes para hacer una importación limpia
        DiagnosticQuestion::truncate();

        $questions = [
            // Excel questions (actualizadas)
            [
                'category' => 'excel',
                'question' => '¿Cuál es la función que permite contar solo las celdas que cumplen una condición?',
                'option_a' => 'CONTAR',
                'option_b' => 'CONTARA',
                'option_c' => 'CONTAR.SI',
                'option_d' => 'SUMA.SI',
                'correct_answer' => 'c',
            ],
            [
                'category' => 'excel',
                'question' => '¿Qué función usarías para devolver el valor más pequeño dentro de un rango?',
                'option_a' => 'MAX',
                'option_b' => 'MIN',
                'option_c' => 'PEQUEÑO',
                'option_d' => 'REDONDEAR',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'excel',
                'question' => '¿Cuál es el atajo para copiar el formato de una celda?',
                'option_a' => 'Ctrl + C',
                'option_b' => 'Ctrl + Shift + C',
                'option_c' => 'F4',
                'option_d' => 'Doble clic en el “Pincel de formato”',
                'correct_answer' => 'd',
            ],
            [
                'category' => 'excel',
                'question' => '¿Qué devuelve la función =HOY()? ',
                'option_a' => 'La fecha y hora actual',
                'option_b' => 'Solo la hora actual',
                'option_c' => 'Solo la fecha actual',
                'option_d' => 'La fecha en formato de texto',
                'correct_answer' => 'c',
            ],
            [
                'category' => 'excel',
                'question' => '¿Qué función permite combinar texto de varias celdas?',
                'option_a' => 'UNIR',
                'option_b' => 'CONCATENAR / CONCAT',
                'option_c' => 'TEXTO',
                'option_d' => 'UNECADENAS',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'excel',
                'question' => '¿Qué hace la función =BUSCARV()? ',
                'option_a' => 'Busca valores horizontalmente',
                'option_b' => 'Busca valores verticalmente',
                'option_c' => 'Ordena valores',
                'option_d' => 'Copia y pega datos',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'excel',
                'question' => '¿Cuál es el símbolo para crear referencias absolutas?',
                'option_a' => '#',
                'option_b' => '$',
                'option_c' => '@',
                'option_d' => '&',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'excel',
                'question' => '¿Qué atajo permite seleccionar toda la hoja?',
                'option_a' => 'Ctrl + A',
                'option_b' => 'Ctrl + H',
                'option_c' => 'Ctrl + E',
                'option_d' => 'Ctrl + Shift + L',
                'correct_answer' => 'a',
            ],
            [
                'category' => 'excel',
                'question' => 'La función SUMAR.SI permite:',
                'option_a' => 'Sumar solo números negativos',
                'option_b' => 'Sumar solo números positivos',
                'option_c' => 'Sumar valores si cumplen una condición',
                'option_d' => 'Sumar texto',
                'correct_answer' => 'c',
            ],
            [
                'category' => 'excel',
                'question' => '¿Para qué sirve la herramienta “Validación de datos”?',
                'option_a' => 'Para proteger la hoja',
                'option_b' => 'Para filtrar datos automáticamente',
                'option_c' => 'Para restringir el tipo de datos permitidos en una celda',
                'option_d' => 'Para eliminar duplicados',
                'correct_answer' => 'c',
            ],
            [
                'category' => 'excel',
                'question' => '¿Qué hace F4 cuando editas una fórmula?',
                'option_a' => 'Cierra Excel',
                'option_b' => 'Repite la última acción',
                'option_c' => 'Alterna entre referencia absoluta/relativa',
                'option_d' => 'Abre el historial de cambios',
                'correct_answer' => 'c',
            ],
            [
                'category' => 'excel',
                'question' => '¿Qué gráfico es ideal para mostrar proporciones de un total?',
                'option_a' => 'Gráfico de barras',
                'option_b' => 'Gráfico circular',
                'option_c' => 'Gráfico de líneas',
                'option_d' => 'Gráfico de dispersión',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'excel',
                'question' => '¿Qué función extrae una cantidad específica de caracteres desde la izquierda?',
                'option_a' => 'DERECHA',
                'option_b' => 'EXTRAE',
                'option_c' => 'IZQUIERDA',
                'option_d' => 'LARGO',
                'correct_answer' => 'c',
            ],
            [
                'category' => 'excel',
                'question' => '¿Qué opción permite mantener filas o columnas fijas al desplazarse?',
                'option_a' => 'Inmovilizar paneles',
                'option_b' => 'Vista previa',
                'option_c' => 'Dividir hoja',
                'option_d' => 'Formato condicional',
                'correct_answer' => 'a',
            ],
            [
                'category' => 'excel',
                'question' => '¿Qué hace el comando “Quitar duplicados”?',
                'option_a' => 'Ordena los datos',
                'option_b' => 'Elimina filas repetidas según columnas seleccionadas',
                'option_c' => 'Elimina celdas vacías',
                'option_d' => 'Convierte texto a columnas',
                'correct_answer' => 'b',
            ],
            // Power BI questions
            [
                'category' => 'powerbi',
                'question' => '¿Qué herramienta permite limpiar, transformar y combinar datos dentro de Power BI?',
                'option_a' => 'Panel de campos',
                'option_b' => 'Power Query',
                'option_c' => 'Modelado',
                'option_d' => 'Visualizaciones',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué es una medida en DAX?',
                'option_a' => 'Un valor estático',
                'option_b' => 'Un cálculo dinámico basado en el contexto',
                'option_c' => 'Una columna',
                'option_d' => 'Un filtro',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué tipo de visualización conviene para mostrar tendencias a lo largo del tiempo?',
                'option_a' => 'Mapa',
                'option_b' => 'Gráfico de líneas',
                'option_c' => 'Matriz',
                'option_d' => 'Dispersión',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué se usa para conectar tablas relacionadas?',
                'option_a' => 'Medidas',
                'option_b' => 'Relaciones',
                'option_c' => 'Panel de filtros',
                'option_d' => 'Visualizaciones',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué permite la vista de Modelado?',
                'option_a' => 'Crear dashboards',
                'option_b' => 'Crear relaciones y medidas',
                'option_c' => 'Exportar informes',
                'option_d' => 'Cambiar temas',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué tabla es fundamental para trabajar con funciones de inteligencia temporal?',
                'option_a' => 'Tabla resumen',
                'option_b' => 'Tabla de medidas',
                'option_c' => 'Tabla calendario',
                'option_d' => 'Tabla duplicada',
                'correct_answer' => 'c',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Cuál es la función principal de Power BI Desktop?',
                'option_a' => 'Ejecutar flujos',
                'option_b' => 'Crear y transformar modelos de datos',
                'option_c' => 'Compartir informes',
                'option_d' => 'Definir permisos',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué visualización es ideal para comparar proporciones?',
                'option_a' => 'Dispersión',
                'option_b' => 'Torta',
                'option_c' => 'Línea',
                'option_d' => 'Mapa',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué es un slicer?',
                'option_a' => 'Un tipo de medida',
                'option_b' => 'Un filtro visual',
                'option_c' => 'Un tipo de archivo',
                'option_d' => 'Un conector',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Para qué sirve CALCULATE en DAX?',
                'option_a' => 'Importar datos',
                'option_b' => 'Cambiar el contexto de cálculo',
                'option_c' => 'Crear gráficos',
                'option_d' => 'Ordenar columnas',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué opción permite que un reporte en Power BI se actualice automáticamente desde la nube?',
                'option_a' => 'Exportar',
                'option_b' => 'Actualización programada',
                'option_c' => 'Publicar manualmente cada día',
                'option_d' => 'Convertir a Excel',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué tipo de gráfico es más útil para comparar categorías?',
                'option_a' => 'Columnas',
                'option_b' => 'Area',
                'option_c' => 'Torta',
                'option_d' => 'Tarjeta',
                'correct_answer' => 'a',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué beneficio tiene usar Power BI para análisis de datos?',
                'option_a' => 'Editar documentos',
                'option_b' => 'Visualizar datos interactivos y conectados',
                'option_c' => 'Crear macros',
                'option_d' => 'Gestión de usuarios',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué se obtiene al crear una relación "uno a muchos"?',
                'option_a' => 'Un filtro',
                'option_b' => 'Un gráfico',
                'option_c' => 'La conexión entre tablas clave',
                'option_d' => 'Una medida',
                'correct_answer' => 'c',
            ],
            [
                'category' => 'powerbi',
                'question' => '¿Qué función permite combinar datos de muchas fuentes distintas?',
                'option_a' => 'Relacionar',
                'option_b' => 'Power Query',
                'option_c' => 'Medidas',
                'option_d' => 'Mapas',
                'correct_answer' => 'b',
            ],
            // Power Automate questions
            [
                'category' => 'powerautomate',
                'question' => '¿Qué es un flujo automatizado?',
                'option_a' => 'Un proceso manual',
                'option_b' => 'Un proceso que se ejecuta cuando ocurre un evento',
                'option_c' => 'Un archivo comprimido',
                'option_d' => 'Un gráfico',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué es un trigger?',
                'option_a' => 'Un paso final',
                'option_b' => 'El evento que activa un flujo',
                'option_c' => 'Una notificación',
                'option_d' => 'Una conexión',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué es un conector en Power Automate?',
                'option_a' => 'Un archivo',
                'option_b' => 'Una aplicación externa que se integra con el flujo',
                'option_c' => 'Un gráfico',
                'option_d' => 'Una carpeta',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué tipo de flujo se activa en un horario definido?',
                'option_a' => 'Flujo automático',
                'option_b' => 'Flujo instantáneo',
                'option_c' => 'Flujo programado',
                'option_d' => 'Flujo de escritorio',
                'correct_answer' => 'c',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué permite la acción "Enviar un correo (V2)" en Outlook?',
                'option_a' => 'Ejecutar consultas',
                'option_b' => 'Notificar automáticamente',
                'option_c' => 'Crear tablas',
                'option_d' => 'Exportar datos',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué tipo de flujo permite ejecutarse con un botón en el móvil?',
                'option_a' => 'Flujo automático',
                'option_b' => 'Flujo instantáneo',
                'option_c' => 'Flujo programado',
                'option_d' => 'Flujo de escritorio',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué debes revisar cuando un flujo falla?',
                'option_a' => 'Historial del flujo y detalles del error',
                'option_b' => 'Ubicación del archivo',
                'option_c' => 'El panel de visualización',
                'option_d' => 'Conexiones de Power BI',
                'correct_answer' => 'a',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué acción permite crear un registro en una lista de SharePoint?',
                'option_a' => 'Crear ítem',
                'option_b' => 'Exportar tabla',
                'option_c' => 'Combinar archivos',
                'option_d' => 'Filtrar datos',
                'correct_answer' => 'a',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué es un flujo de escritorio?',
                'option_a' => 'Un programa de gráficos',
                'option_b' => 'Una automatización local con acciones del computador',
                'option_c' => 'Un panel de análisis',
                'option_d' => 'Un conector externo',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué permite la acción "Agregar fila a una tabla" en Excel Online?',
                'option_a' => 'Crear una tabla dinámica',
                'option_b' => 'Insertar datos automáticamente',
                'option_c' => 'Ejecutar consultas SQL',
                'option_d' => 'Aplicar formato',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué caracteriza a un flujo automático?',
                'option_a' => 'Se ejecuta con un botón',
                'option_b' => 'Se activa según un evento externo',
                'option_c' => 'Se ejecuta en un horario',
                'option_d' => 'Solo funciona en escritorio',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué debes tener para usar un conector premium?',
                'option_a' => 'Permisos del equipo',
                'option_b' => 'Licencias adicionales',
                'option_c' => 'Un archivo PDF',
                'option_d' => 'Una cuenta de Gmail',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué permite Power Automate en una organización?',
                'option_a' => 'Crear dashboards',
                'option_b' => 'Automatizar procesos repetitivos',
                'option_c' => 'Extraer datos de bases clínicas',
                'option_d' => 'Convertir archivos',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué herramienta permite monitorear el comportamiento del flujo paso a paso?',
                'option_a' => 'Editor de Excel',
                'option_b' => 'Historial del flujo',
                'option_c' => 'Power BI',
                'option_d' => 'OneDrive',
                'correct_answer' => 'b',
            ],
            [
                'category' => 'powerautomate',
                'question' => '¿Qué opción es necesaria para que un flujo funcione correctamente?',
                'option_a' => 'Un tema de color',
                'option_b' => 'Un trigger inicial',
                'option_c' => 'Un archivo en PDF',
                'option_d' => 'Una cuenta local',
                'correct_answer' => 'b',
            ],
        ];

        foreach ($questions as $question) {
            DiagnosticQuestion::create($question);
        }
    }
}
